from judge.tasks.contest import *
from judge.tasks.demo import *
from judge.tasks.submission import *
from judge.tasks.chatbot import *
from judge.tasks.llm import *
from judge.tasks.package_import import *
from judge.tasks.quiz_import import *
from judge.tasks.semantic_search import *
from judge.tasks.review import *
from judge.tasks.contest_review import *
