from judge.tasks.contest import *
from judge.tasks.demo import *
from judge.tasks.submission import *
from judge.tasks.chatbot import *
from judge.tasks.llm import *
from judge.tasks.package_import import *
from judge.tasks.quiz_import import *
from judge.tasks.semantic_search import *
from judge.tasks.review import *
from judge.tasks.contest_review import *
from judge.tasks.username_moderation import *
from judge.tasks.comment_moderation import *
from judge.tasks.chat_moderation import *
from judge.tasks.post_moderation import *
from judge.tasks.maintenance import *
from judge.tasks.magazine import *
from judge.tasks.email import *
