# Generated by Django 2.2.9 on 2020-03-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0102_fix_custom_validator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problemdata",
            old_name="custom_valid",
            new_name="custom_validator",
        ),
    ]
