# Generated by Django 2.2.25 on 2022-03-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0118_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="hide_problem_tags",
            field=models.BooleanField(
                default=True,
                help_text="Whether problem tags should be hidden by default.",
                verbose_name="hide problem tags",
            ),
        ),
    ]
