# Generated by Django 2.2.25 on 2022-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0124_auto_20220602_1116"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemdata",
            name="fileio_input",
            field=models.TextField(
                blank=True,
                help_text="Leave empty for stdin",
                null=True,
                verbose_name="input file name",
            ),
        ),
        migrations.AlterField(
            model_name="problemdata",
            name="fileio_output",
            field=models.TextField(
                blank=True,
                help_text="Leave empty for stdout",
                null=True,
                verbose_name="output file name",
            ),
        ),
    ]
