# Generated by Django 2.2.25 on 2022-08-31 03:48

from django.db import migrations, models
import judge.models.problem
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0129_auto_20220622_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pdf_description',
            field=models.FileField(blank=True, null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem.problem_directory_file, verbose_name='pdf statement'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, verbose_name='problem body'),
        ),
    ]
