# Generated by Django 2.2.28 on 2022-09-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0132_auto_20220915_1837'),
        ('judge', '0132_auto_20220915_1349'),
    ]

    operations = [
    ]
