# Generated by Django 2.2.28 on 2022-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0133_merge_20220916_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='is delete'),
        ),
    ]
