# Generated by Django 2.2.28 on 2022-10-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0134_blogpost_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_delete',
        ),
    ]
