# Generated by Django 3.2.16 on 2022-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0138_bookmark_makebookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="freeze_after",
            field=models.DurationField(
                blank=True,
                help_text="Format hh:mm:ss. For example, if you want to freeze contest after 2 hours, enter 02:00:00",
                null=True,
                verbose_name="freeze after",
            ),
        ),
    ]
