# Generated by Django 3.2.16 on 2022-11-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0139_contest_freeze_after"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="format_name",
            field=models.CharField(
                choices=[
                    ("atcoder", "AtCoder"),
                    ("default", "Default"),
                    ("ecoo", "ECOO"),
                    ("icpc", "ICPC"),
                    ("ioi", "IOI"),
                    ("ioi16", "New IOI"),
                ],
                default="default",
                help_text="The contest format module to use.",
                max_length=32,
                verbose_name="contest format",
            ),
        ),
    ]
