# Generated by Django 3.2.16 on 2022-12-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0141_contestproblem_frozen_subtasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipation",
            name="format_data_final",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="same as format_data, but including frozen results",
            ),
        ),
    ]
