# Generated by Django 3.2.16 on 2022-12-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0142_contestparticipation_format_data_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipation",
            name="cumtime_final",
            field=models.PositiveIntegerField(
                default=0, verbose_name="final cumulative time"
            ),
        ),
        migrations.AddField(
            model_name="contestparticipation",
            name="score_final",
            field=models.FloatField(default=0, verbose_name="final score"),
        ),
    ]
