# Generated by Django 3.2.16 on 2023-01-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0143_auto_20221229_0153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestproblem",
            name="frozen_subtasks",
        ),
        migrations.AddField(
            model_name="contestproblem",
            name="hidden_subtasks",
            field=models.CharField(
                blank=True,
                help_text="Separated by commas, e.g: 2, 3",
                max_length=20,
                null=True,
                verbose_name="hidden subtasks",
            ),
        ),
    ]
