# Generated by Django 3.2.16 on 2023-01-25 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0145_alter_organization_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                help_text="Organization name shown in URL",
                max_length=128,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[-a-zA-Z0-9]+$", "Only alphanumeric and hyphens"
                    )
                ],
                verbose_name="organization slug",
            ),
        ),
    ]
