# Generated by Django 3.2.17 on 2023-02-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_alter_courseassignment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserole',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.course', verbose_name='course'),
        ),
    ]
