# Generated by Django 3.2.18 on 2023-02-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0152_migrate_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="page",
        ),
        migrations.AlterField(
            model_name="commentlock",
            name="page",
            field=models.CharField(
                db_index=True, max_length=30, verbose_name="associated page"
            ),
        ),
    ]
