# Generated by Django 3.2.18 on 2023-03-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0154_add_submission_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="output_only",
            field=models.BooleanField(
                help_text="Support output-only problem",
                null=True,
                verbose_name="is output only",
            ),
        ),
    ]
