# Generated by Django 3.2.18 on 2023-07-31 18:07

import django.core.validators
from django.db import migrations, models
import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0155_output_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="signature_handler",
            field=models.FileField(
                blank=True,
                null=True,
                storage=judge.utils.problem_data.ProblemDataStorage(),
                upload_to=judge.models.problem_data.problem_directory_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["cpp"]
                    )
                ],
                verbose_name="signature handler",
            ),
        ),
        migrations.AddField(
            model_name="problemdata",
            name="signature_header",
            field=models.FileField(
                blank=True,
                null=True,
                storage=judge.utils.problem_data.ProblemDataStorage(),
                upload_to=judge.models.problem_data.problem_directory_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["h"]
                    )
                ],
                verbose_name="signature header",
            ),
        ),
    ]
