# Generated by Django 3.2.18 on 2023-08-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0156_auto_20230801_0107"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="use_ioi_signature",
            field=models.BooleanField(
                help_text="Use IOI Signature",
                null=True,
                verbose_name="is IOI signature",
            ),
        ),
    ]
