# Generated by Django 3.2.18 on 2023-08-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0162_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_change_pending",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
