# Generated by Django 3.2.18 on 2023-08-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0164_show_testcase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestproblem",
            name="output_prefix_override",
        ),
    ]
