# Generated by Django 3.2.18 on 2023-09-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0167_ultimate_contest_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="css_background",
            field=models.TextField(
                blank=True,
                help_text='CSS custom background properties: url("image_url"), color, etc',
                max_length=300,
                null=True,
                verbose_name="Custom background",
            ),
        ),
    ]
