# Generated by Django 3.2.18 on 2023-09-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0168_css_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="public_scoreboard",
            field=models.BooleanField(
                default=False,
                help_text="Ranking page is public even for private contests.",
                verbose_name="public scoreboard",
            ),
        ),
    ]
