# Generated by Django 3.2.21 on 2023-10-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0169_public_scoreboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestsSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scores", models.JSONField(blank=True, null=True)),
                ("key", models.CharField(max_length=20, unique=True)),
                ("contests", models.ManyToManyField(to="judge.Contest")),
            ],
        ),
    ]
