# Generated by Django 3.2.18 on 2023-10-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0172_index_rating"),
    ]

    operations = [
        migrations.RunSQL(
            (
                "CREATE FULLTEXT INDEX IF NOT EXISTS code_name_index ON judge_problem (code, name)",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            (
                "CREATE FULLTEXT INDEX IF NOT EXISTS key_name_index ON judge_contest (`key`, name)",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
