# Generated by Django 3.2.18 on 2023-11-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0174_contest_summary_result"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_unlisted", "performance_points"],
                name="judge_profi_is_unli_d4034c_idx",
            ),
        ),
    ]
