# Generated by Django 3.2.18 on 2024-01-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0177_test_formatter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user_script",
        ),
    ]
