# Generated by Django 3.2.18 on 2024-02-15 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0179_submission_result_lang_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="course title")),
                ("content", models.TextField(verbose_name="course content")),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("points", models.IntegerField(verbose_name="points")),
            ],
        ),
        migrations.RemoveField(
            model_name="courseresource",
            name="course",
        ),
        migrations.RemoveField(
            model_name="course",
            name="ending_time",
        ),
        migrations.AlterField(
            model_name="courserole",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="judge.course",
                verbose_name="course",
            ),
        ),
        migrations.DeleteModel(
            name="CourseAssignment",
        ),
        migrations.DeleteModel(
            name="CourseResource",
        ),
        migrations.AddField(
            model_name="courselesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="judge.course",
                verbose_name="course",
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="problems",
            field=models.ManyToManyField(to="judge.Problem"),
        ),
        migrations.AlterUniqueTogether(
            name="courserole",
            unique_together={("course", "user")},
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="problems",
            field=models.ManyToManyField(blank=True, to="judge.Problem"),
        ),
    ]
