# Generated by Django 3.2.18 on 2024-02-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0180_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="math_engine",
        ),
        migrations.AlterField(
            model_name="course",
            name="about",
            field=models.TextField(verbose_name="course description"),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="judge.course",
                verbose_name="course",
            ),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="problems",
            field=models.ManyToManyField(
                blank=True, to="judge.Problem", verbose_name="problem"
            ),
        ),
        migrations.AlterField(
            model_name="courserole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_roles",
                to="judge.profile",
                verbose_name="user",
            ),
        ),
    ]
