# Generated by Django 3.2.18 on 2024-03-23 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0183_rename_custom_checker_cpp"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="rate_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of submissions per minute. Leave empty if you don't want rate limit.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="rate limit",
            ),
        ),
    ]
