# Generated by Django 3.2.18 on 2024-04-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0184_contest_rate_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationprofile",
            old_name="users",
            new_name="profile",
        ),
    ]
