# Generated by Django 3.2.18 on 2024-04-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0186_change_about_fields_max_len"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_banned_problem_voting",
        ),
        migrations.CreateModel(
            name="ProfileInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tshirt_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Small (S)"),
                            ("M", "Medium (M)"),
                            ("L", "Large (L)"),
                            ("XL", "Extra Large (XL)"),
                            ("XXL", "2 Extra Large (XXL)"),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name="t-shirt size",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="address"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="judge.profile",
                        verbose_name="profile associated",
                    ),
                ),
            ],
        ),
    ]
