# Generated by Django 3.2.21 on 2024-07-08 00:05

from django.db import migrations, models
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0188_official_contest"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="organization_image",
            field=models.ImageField(
                null=True, upload_to=judge.models.profile.organization_image_path
            ),
        ),
    ]
