# Generated by Django 3.2.18 on 2024-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0189_organization_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="read",
        ),
    ]
