# Generated by Django 3.2.21 on 2024-09-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0191_deprecate_old_org_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLessonProblem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("score", models.IntegerField(default=0, verbose_name="score")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_problems",
                        to="judge.courselesson",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.problem"
                    ),
                ),
            ],
        ),
    ]
