# Generated by Django 3.2.21 on 2024-09-30 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0193_remove_old_course_problems"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="is_in_course",
            field=models.BooleanField(default=False, verbose_name="contest in course"),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="publicly visible"),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="content",
            field=models.TextField(verbose_name="lesson content"),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="title",
            field=models.TextField(verbose_name="lesson title"),
        ),
        migrations.CreateModel(
            name="CourseContest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("points", models.IntegerField(verbose_name="points")),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course",
                        to="judge.contest",
                        unique=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contests",
                        to="judge.course",
                    ),
                ),
            ],
        ),
    ]
