# Generated by Django 3.2.25 on 2024-10-11 04:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judge.models.problem_data
import judge.utils.problem_data


def create_signature_graders(apps, schema_editor):
    ProblemData = apps.get_model("judge", "ProblemData")
    ProblemSignatureGrader = apps.get_model("judge", "ProblemSignatureGrader")

    for problem_data in ProblemData.objects.filter(use_ioi_signature=True):
        ProblemSignatureGrader.objects.create(
            language="c",
            handler=problem_data.signature_handler,
            header=problem_data.signature_header,
            problem=problem_data.problem,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0194_course_contest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemSignatureGrader",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("c", "C/C++"),
                            ("java", "Java"),
                            ("python", "Python"),
                        ],
                        max_length=10,
                        verbose_name="signature language",
                    ),
                ),
                (
                    "handler",
                    models.FileField(
                        storage=judge.utils.problem_data.ProblemDataStorage(),
                        upload_to=judge.models.problem_data.problem_directory_file,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["cpp", "c", "java", "py"]
                            )
                        ],
                        verbose_name="signature handler",
                    ),
                ),
                (
                    "header",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=judge.utils.problem_data.ProblemDataStorage(),
                        upload_to=judge.models.problem_data.problem_directory_file,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["h"]
                            )
                        ],
                        verbose_name="signature header",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_graders",
                        to="judge.problem",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_signature_graders),
    ]
