# Generated by Django 3.2.25 on 2024-11-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0195_signature_grader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemdata",
            name="checker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("floats", "Floats"),
                    ("floatsabs", "Floats (absolute)"),
                    ("floatsrel", "Floats (relative)"),
                    ("rstripped", "Non-trailing spaces"),
                    ("sorted", "Unordered"),
                    ("identical", "Byte identical"),
                    ("linecount", "Line-by-line"),
                    ("custom", "Custom checker (PY)"),
                    ("customcpp", "Custom checker (CPP)"),
                    ("interact", "Interactive"),
                    ("testlib", "Testlib"),
                    ("interacttl", "Interactive (Testlib)"),
                ],
                max_length=10,
                verbose_name="checker",
            ),
        ),
        migrations.AlterField(
            model_name="problemtestcase",
            name="checker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("floats", "Floats"),
                    ("floatsabs", "Floats (absolute)"),
                    ("floatsrel", "Floats (relative)"),
                    ("rstripped", "Non-trailing spaces"),
                    ("sorted", "Unordered"),
                    ("identical", "Byte identical"),
                    ("linecount", "Line-by-line"),
                    ("custom", "Custom checker (PY)"),
                    ("customcpp", "Custom checker (CPP)"),
                    ("interact", "Interactive"),
                    ("testlib", "Testlib"),
                    ("interacttl", "Interactive (Testlib)"),
                ],
                max_length=10,
                verbose_name="checker",
            ),
        ),
    ]
