# Generated by Django 4.2.17 on 2025-01-04 01:11

from django.db import migrations
from django.db.models import Sum


def recalculate_pagevote_scores(apps, schema_editor):
    # Get the PageVote and PageVoteVoter models
    PageVote = apps.get_model("judge", "PageVote")
    PageVoteVoter = apps.get_model("judge", "PageVoteVoter")

    for pagevote in PageVote.objects.all():
        score_sum = (
            PageVoteVoter.objects.filter(pagevote=pagevote).aggregate(Sum("score"))[
                "score__sum"
            ]
            or 0
        )
        pagevote.score = score_sum
        pagevote.save()


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0197_remove_bookmark_page_bookmark_users_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagevote",
            name="page",
        ),
        migrations.RunPython(recalculate_pagevote_scores),
    ]
