# Generated by Django 4.2.17 on 2025-01-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("judge", "0198_remove_pagevote_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocker_id", models.PositiveIntegerField()),
                ("blocked_id", models.PositiveIntegerField()),
                (
                    "blocked_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_blocks",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "blocker_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocker_blocks",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "block",
                "verbose_name_plural": "blocks",
                "indexes": [
                    models.Index(
                        fields=["blocker_type", "blocker_id"], name="blocker_idx"
                    ),
                    models.Index(
                        fields=["blocked_type", "blocked_id"], name="blocked_idx"
                    ),
                ],
                "unique_together": {
                    ("blocker_type", "blocker_id", "blocked_type", "blocked_id")
                },
            },
        ),
    ]
