# Generated by Django 4.2.17 on 2025-01-08 23:52

from django.db import migrations
from django.db.models import Max


def recalculate_submission_runtimes(apps, schema_editor):
    # Calculate the new time (max of test case times)
    Submission = apps.get_model("judge", "Submission")
    SubmissionTestCase = apps.get_model("judge", "SubmissionTestCase")

    for submission in Submission.objects.all():
        test_cases = SubmissionTestCase.objects.filter(submission=submission)

        if test_cases.exists():
            max_time = test_cases.aggregate(Max("time"))["time__max"]
        else:
            max_time = 0

        submission.time = max_time
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0199_block"),
    ]

    operations = [
        migrations.RunPython(recalculate_submission_runtimes),
    ]
