# Generated by Django 4.2.17 on 2025-01-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0200_recalculate_submission_time"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["problem", "result", "points"],
                name="judge_submi_problem_23235d_idx",
            ),
        ),
    ]
