# Generated by Django 4.2.17 on 2025-03-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0203_remove_organizationprofile_last_visit"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="judge_comme_content_2dce05_idx",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id", "hidden"],
                name="judge_comme_content_50dccb_idx",
            ),
        ),
    ]
