# Generated by Django 4.2.17 on 2025-06-13 06:08

from django.db import migrations, models
import judge.models.course


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0205_change_cumtime_to_bigint"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=judge.models.course.course_image_path,
                verbose_name="course image",
            ),
        ),
        migrations.RemoveField(
            model_name="course",
            name="image_url",
        ),
    ]
