# Generated by Django 4.2.17 on 2025-06-24 22:26

from django.db import migrations, models
import django.db.models.deletion


def migrate_email_change_pending(apps, schema_editor):
    Profile = apps.get_model("judge", "Profile")
    EmailChangeRequest = apps.get_model("judge", "EmailChangeRequest")

    profiles_with_pending_email = Profile.objects.exclude(
        email_change_pending__isnull=True
    ).exclude(email_change_pending="")

    for profile in profiles_with_pending_email:
        EmailChangeRequest.objects.create(
            profile=profile, new_email=profile.email_change_pending
        )


def reverse_migration(apps, schema_editor):
    Profile = apps.get_model("judge", "Profile")
    EmailChangeRequest = apps.get_model("judge", "EmailChangeRequest")

    # Remove all EmailChangeRequest instances and restore email_change_pending
    for email_change_request in EmailChangeRequest.objects.all():
        profile = email_change_request.profile
        profile.email_change_pending = email_change_request.new_email
        profile.save()

    # Delete all EmailChangeRequest instances
    EmailChangeRequest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0206_replace_course_image_url_with_image_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(max_length=254, verbose_name="new email address"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_requests",
                        to="judge.profile",
                        verbose_name="user profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "email change request",
                "verbose_name_plural": "email change requests",
            },
        ),
        migrations.RunPython(migrate_email_change_pending, reverse_migration),
        migrations.RemoveField(
            model_name="profile",
            name="email_change_pending",
        ),
    ]
