# Generated by Django 4.2.17 on 2025-06-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0206_replace_course_image_url_with_image_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="generator_script",
            field=models.TextField(blank=True, verbose_name="generator script"),
        ),
    ]
