# Generated by Django 4.2.17 on 2025-07-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0207_add_generator_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="short_circuit",
            field=models.BooleanField(
                default=False,
                help_text="Stop judging when the first test case fails (ICPC-style). If disabled, all test cases will be judged.",
                verbose_name="stop on first fail",
            ),
        ),
    ]
