# Generated by Django 4.2.17 on 2025-07-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0207_remove_profile_email_change_pending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="generator_script",
            field=models.TextField(blank=True, verbose_name="generator script"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="short_circuit",
            field=models.BooleanField(
                default=False,
                help_text="Stop judging when the first test case fails (ICPC-style). If disabled, all test cases will be judged.",
                verbose_name="stop on first fail",
            ),
        ),
    ]
