# Generated by Django 4.2.17 on 2025-09-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0208_problemdata_generator_script_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="If not empty, only these organizations may see the course",
                to="judge.organization",
                verbose_name="organizations",
            ),
        ),
    ]
