# Generated by Django 4.2.17 on 2025-12-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0210_improve_notification_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VolunteerProblemVote",
        ),
    ]
