# Generated by Django 4.2.17 on 2025-12-24 03:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judge.models.quiz


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0211_remove_volunteer_problem_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLessonQuiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="0 for unlimited attempts",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Max Attempts",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        help_text="Points awarded in lesson for completing quiz",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Lesson Points",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order in lesson",
                        verbose_name="Order",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visible"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_quizzes",
                        to="judge.courselesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Lesson Quiz",
                "verbose_name_plural": "Course Lesson Quizzes",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="A short, unique code for the quiz, used in the URL after /quiz/",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9]+$", "Quiz code must be ^[a-z0-9]+$"
                            )
                        ],
                        verbose_name="quiz code",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="The full title of the quiz, as shown in the quiz list",
                        max_length=255,
                        verbose_name="Quiz Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Instructions or description shown before starting",
                        verbose_name="Description",
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=0,
                        help_text="0 for no time limit",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Time Limit (minutes)",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False,
                        help_text="Randomize question order for each attempt",
                        verbose_name="Shuffle Questions",
                    ),
                ),
                (
                    "is_shown_answer",
                    models.BooleanField(
                        default=False,
                        help_text="Whether answers and explanations are shown to students after submission",
                        verbose_name="Show Answers",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="These users will be able to edit the quiz and be listed as authors",
                        related_name="authored_quizzes",
                        to="judge.profile",
                        verbose_name="authors",
                    ),
                ),
                (
                    "curators",
                    models.ManyToManyField(
                        blank=True,
                        help_text="These users will be able to edit the quiz, but not be listed as authors",
                        related_name="curated_quizzes",
                        to="judge.profile",
                        verbose_name="curators",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True,
                        help_text="Student's answer (format depends on question type)",
                        verbose_name="Answer",
                    ),
                ),
                (
                    "points",
                    models.FloatField(
                        default=0,
                        help_text="Points awarded for this answer",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Points",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True,
                        help_text="Auto-graded or manually graded result",
                        null=True,
                        verbose_name="Is Correct",
                    ),
                ),
                (
                    "partial_credit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0.0 to 1.0 for partial credit",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Partial Credit",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Instructor feedback for this answer",
                        verbose_name="Feedback",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now=True, verbose_name="Answered At"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Graded At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Answer",
                "verbose_name_plural": "Quiz Answers",
                "ordering": ["attempt", "question"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MC", "Multiple Choice"),
                            ("MA", "Multiple Answer"),
                            ("SA", "Short Answer"),
                            ("ES", "Essay"),
                            ("TF", "True/False"),
                        ],
                        max_length=2,
                        verbose_name="Question Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for question management",
                        max_length=255,
                        verbose_name="Question Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual question text shown to students",
                        verbose_name="Question Content",
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        help_text="Answer choices for MC/MA/TF questions",
                        null=True,
                        verbose_name="Choices",
                    ),
                ),
                (
                    "correct_answers",
                    models.JSONField(
                        blank=True,
                        help_text="Correct answer(s) for the question",
                        null=True,
                        verbose_name="Correct Answers",
                    ),
                ),
                (
                    "default_points",
                    models.FloatField(
                        default=1.0,
                        help_text="Default point value when added to quizzes",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Default Points",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this question is publicly visible",
                        verbose_name="Is Public",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation shown to students after completion",
                        verbose_name="Explanation",
                    ),
                ),
                (
                    "shuffle_choices",
                    models.BooleanField(
                        default=False,
                        help_text="Randomize choice order for this question",
                        verbose_name="Shuffle Choices",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for categorizing questions",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="These users will be able to edit the question and be listed as authors",
                        related_name="authored_quiz_questions",
                        to="judge.profile",
                        verbose_name="authors",
                    ),
                ),
                (
                    "curators",
                    models.ManyToManyField(
                        blank=True,
                        help_text="These users will be able to edit the question, but not be listed as authors",
                        related_name="curated_quiz_questions",
                        to="judge.profile",
                        verbose_name="curators",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Question",
                "verbose_name_plural": "Quiz Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="contestproblem",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contests",
                to="judge.problem",
                verbose_name="problem",
            ),
        ),
        migrations.CreateModel(
            name="QuizQuestionAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=1,
                        help_text="Points for this question in this quiz",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Points",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order in quiz (if not shuffled)",
                        verbose_name="Order",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_assignments",
                        to="judge.quizquestion",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="judge.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Question Assignment",
                "verbose_name_plural": "Quiz Question Assignments",
                "ordering": ["order", "id"],
                "unique_together": {("quiz", "question")},
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(default=1, verbose_name="Attempt Number"),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When submitted or timed out",
                        null=True,
                        verbose_name="End Time",
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.IntegerField(default=0, verbose_name="Time Limit (minutes)"),
                ),
                (
                    "is_submitted",
                    models.BooleanField(default=False, verbose_name="Is Submitted"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Max Score",
                    ),
                ),
                (
                    "contest_participation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="judge.contestparticipation",
                    ),
                ),
                (
                    "lesson_quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="judge.courselessonquiz",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="judge.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="judge.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Attempt",
                "verbose_name_plural": "Quiz Attempts",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswerFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=judge.models.quiz.quiz_answer_file_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original Filename"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="judge.quizanswer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Answer File",
                "verbose_name_plural": "Quiz Answer Files",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="judge.quizattempt",
            ),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_quiz_answers",
                to="judge.profile",
                verbose_name="Graded By",
            ),
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="judge.quizquestion",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                related_name="quizzes",
                through="judge.QuizQuestionAssignment",
                to="judge.quizquestion",
                verbose_name="Questions",
            ),
        ),
        migrations.AddField(
            model_name="courselessonquiz",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_lessons",
                to="judge.quiz",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestproblem",
            unique_together={("problem", "contest")},
        ),
        migrations.AddField(
            model_name="contestproblem",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_quizzes",
                to="judge.quiz",
                verbose_name="quiz",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestproblem",
            unique_together={("problem", "contest"), ("quiz", "contest")},
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(
                fields=["question_type"], name="judge_quizq_questio_f187b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(
                fields=["is_public"], name="judge_quizq_is_publ_a734fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["user", "quiz"], name="judge_quiza_user_id_811721_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["quiz", "is_submitted"], name="judge_quiza_quiz_id_a3b83b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizanswer",
            unique_together={("attempt", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="courselessonquiz",
            unique_together={("lesson", "quiz")},
        ),
    ]
