# Generated by Django 4.2.17 on 2025-12-27 00:12

from django.db import migrations, models
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0212_add_quiz_models_and_alter_contestproblem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="css_background",
        ),
        migrations.AddField(
            model_name="profile",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=judge.models.profile.profile_background_path,
                verbose_name="Background image",
            ),
        ),
    ]
