# Generated by Django 4.2.17 on 2025-12-27 00:18

from django.db import migrations, models
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0213_add_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=judge.models.profile.organization_cover_image_path,
                verbose_name="Cover image",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=judge.models.profile.organization_image_path,
                verbose_name="Organization image",
            ),
        ),
    ]
