# Generated by Django 4.2.27 on 2025-12-31 07:54

from django.db import migrations, models
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0215_add_community_and_moderators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="is_community",
            field=models.BooleanField(
                default=False,
                help_text="Communities are always open and focus on discussions rather than contests/problems",
                verbose_name="community",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=judge.models.profile.profile_image_path,
                verbose_name="Profile image",
            ),
        ),
    ]
