# Generated by Django 4.2.27 on 2025-12-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("judge", "0216_add_blank_to_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationModerationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="object ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("hide_comment", "Hide Comment"),
                            ("unhide_comment", "Unhide Comment"),
                            ("approve_post", "Approve Post"),
                            ("reject_post", "Reject Post"),
                            ("skip", "Skipped"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="LLM explanation or moderator note",
                        verbose_name="reason",
                    ),
                ),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="True if action was taken by LLM",
                        verbose_name="automated",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if action was automated by LLM",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to="judge.profile",
                        verbose_name="moderator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="judge.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "moderation log",
                "verbose_name_plural": "moderation logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="judge_organ_organiz_2bc4cf_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="judge_organ_content_faeb00_idx",
                    ),
                ],
            },
        ),
    ]
