# Generated by Django 4.2.27 on 2025-12-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0217_organizationmoderationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_rejected",
            field=models.BooleanField(
                default=False,
                help_text="True if post was rejected by moderator",
                verbose_name="rejected",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("add_blog", "Added a post"),
                    ("added_to_group", "You are added to a group"),
                    ("comment", "You have a new comment"),
                    ("delete_blog", "Deleted a post"),
                    ("reject_blog", "Rejected a post"),
                    ("approve_blog", "Approved a post"),
                    ("edit_blog", "Edited a post"),
                    ("hide_comment", "Your comment was hidden"),
                    ("mention", "Mentioned you"),
                    ("organization", "Organization"),
                    ("problem", "Problem"),
                    ("reply", "Replied you"),
                    ("ticket", "Ticket"),
                    ("problem_public", "Problem visibility changed"),
                    ("problem_private", "Problem visibility changed"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmoderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("hide_comment", "Hide Comment"),
                    ("unhide_comment", "Unhide Comment"),
                    ("keep_comment", "Keep Comment"),
                    ("approve_post", "Approve Post"),
                    ("reject_post", "Reject Post"),
                    ("skip", "Skipped"),
                ],
                max_length=20,
                verbose_name="action",
            ),
        ),
    ]
