# Generated by Django 4.2.17 on 2026-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0218_add_is_rejected_to_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="default_points",
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether the quiz is publicly visible to all users",
                verbose_name="publicly visible",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="testers",
            field=models.ManyToManyField(
                blank=True,
                help_text="These users will be able to view and test the quiz, but not edit it",
                related_name="tested_quizzes",
                to="judge.profile",
                verbose_name="testers",
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="grading_strategy",
            field=models.CharField(
                choices=[
                    ("all_or_nothing", "All or Nothing"),
                    ("partial_credit", "Partial Credit (with penalty)"),
                    ("right_minus_wrong", "Right Minus Wrong"),
                    ("correct_only", "Correct Only (no penalty)"),
                ],
                default="all_or_nothing",
                help_text="How to calculate score for multiple answer questions",
                max_length=20,
                verbose_name="Grading Strategy",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("add_blog", "Added a post"),
                    ("added_to_group", "You are added to a group"),
                    ("comment", "You have a new comment"),
                    ("delete_blog", "Deleted a post"),
                    ("reject_blog", "Rejected a post"),
                    ("approve_blog", "Approved a post"),
                    ("edit_blog", "Edited a post"),
                    ("hide_comment", "Your comment was hidden"),
                    ("mention", "Mentioned you"),
                    ("organization", "Organization"),
                    ("problem", "Problem"),
                    ("reply", "Replied you"),
                    ("ticket", "Ticket"),
                    ("problem_public", "Problem visibility changed"),
                    ("problem_private", "Problem visibility changed"),
                    ("quiz_needs_grading", "Quiz answer needs grading"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="category",
            ),
        ),
    ]
