# Generated by Django 4.2.27 on 2026-03-03 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0223_migrate_to_media_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="testcase_validator",
            field=models.FileField(
                blank=True,
                null=True,
                storage=judge.utils.problem_data.ProblemDataStorage(),
                upload_to=judge.models.problem_data.problem_directory_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["cpp", "c", "py"]
                    )
                ],
                verbose_name="testcase validator",
            ),
        ),
        migrations.AddField(
            model_name="problemdata",
            name="testcase_validator_language",
            field=models.CharField(
                blank=True,
                choices=[("cpp", "C/C++"), ("python", "Python")],
                max_length=10,
                verbose_name="validator language",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dynamic_effect",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("snowflakes", "Snowflakes"),
                    ("snow", "Snow"),
                    ("cherry_blossoms", "Cherry Blossoms"),
                    ("rain", "Rain"),
                    ("fireflies", "Fireflies"),
                    ("lunar_new_year", "Lunar New Year"),
                ],
                default="none",
                max_length=30,
                verbose_name="Dynamic effect",
            ),
        ),
        migrations.CreateModel(
            name="ProblemValidation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validate_id",
                    models.CharField(db_index=True, max_length=36, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("V", "Validating"),
                            ("D", "Done"),
                            ("E", "Error"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                ("total_cases", models.IntegerField(default=0)),
                ("passed", models.BooleanField(null=True)),
                ("failed_count", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="judge.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemValidationResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case", models.IntegerField()),
                ("batch", models.IntegerField(null=True)),
                ("status", models.CharField(max_length=10)),
                ("feedback", models.TextField(blank=True)),
                (
                    "validation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="judge.problemvalidation",
                    ),
                ),
            ],
            options={
                "unique_together": {("validation", "case")},
            },
        ),
    ]
