# Generated by Django 4.2.27 on 2026-03-03 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0224_problemdata_testcase_validator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemdata",
            name="testcase_validator",
            field=models.FileField(
                blank=True,
                null=True,
                storage=judge.utils.problem_data.ProblemDataStorage(),
                upload_to=judge.models.problem_data.problem_directory_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["cpp", "py"]
                    )
                ],
                verbose_name="testcase validator",
            ),
        ),
        migrations.CreateModel(
            name="ProblemSolutionCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="display order")),
                (
                    "source_code",
                    models.TextField(max_length=65536, verbose_name="source code"),
                ),
                (
                    "expected_result",
                    models.CharField(
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RTE", "Runtime Error"),
                            ("OLE", "Output Limit Exceeded"),
                            ("IR", "Invalid Return"),
                        ],
                        max_length=3,
                        verbose_name="expected result",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.language",
                        verbose_name="language",
                    ),
                ),
                (
                    "last_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="judge.submission",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_codes",
                        to="judge.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
