# Generated by Django 4.2.27 on 2026-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0225_problemsolutioncode"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemsolutioncode",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="name"
            ),
        ),
    ]
