# Generated by Django 4.2.27 on 2026-03-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0226_problemsolutioncode_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("A", "Approved"),
                            ("R", "Rejected"),
                        ],
                        db_index=True,
                        default="P",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="admin feedback"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "problem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_request",
                        to="judge.problem",
                        verbose_name="problem",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_requests",
                        to="judge.profile",
                        verbose_name="requested by",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_public_requests",
                        to="judge.profile",
                        verbose_name="reviewed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "public request",
                "verbose_name_plural": "public requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
