# Generated by Django 4.2.29 on 2026-03-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0227_add_public_request_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contribution_points",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("add_blog", "Added a post"),
                    ("added_to_group", "You are added to a group"),
                    ("comment", "You have a new comment"),
                    ("delete_blog", "Deleted a post"),
                    ("reject_blog", "Rejected a post"),
                    ("approve_blog", "Approved a post"),
                    ("edit_blog", "Edited a post"),
                    ("hide_comment", "Your comment was hidden"),
                    ("mention", "Mentioned you"),
                    ("organization", "Organization"),
                    ("problem", "Problem"),
                    ("reply", "Replied you"),
                    ("ticket", "Ticket"),
                    ("problem_public", "Problem visibility changed"),
                    ("problem_private", "Problem visibility changed"),
                    ("quiz_needs_grading", "Quiz answer needs grading"),
                    ("public_request_new", "New public request"),
                    ("public_request_approved", "Public request approved"),
                    ("public_request_rejected", "Public request rejected"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="category",
            ),
        ),
    ]
