# Generated by Django 4.2.29 on 2026-03-16 20:20

from django.db import migrations, models
from django.db.models.functions import Length, Substr


def truncate_long_about(apps, schema_editor):
    """Truncate existing about fields that exceed 1000 characters."""
    Profile = apps.get_model("judge", "Profile")
    Profile.objects.annotate(about_len=Length("about")).filter(
        about_len__gt=1000
    ).update(about=Substr("about", 1, 1000))


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0228_add_contribution_points"),
    ]

    operations = [
        migrations.RunPython(truncate_long_about, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="self-description"
            ),
        ),
    ]
