# Generated by Django 4.2.29 on 2026-03-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0229_reduce_profile_about_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_unlisted", "problem_count"],
                name="judge_profi_is_unli_7e41ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_unlisted", "rating"], name="judge_profi_is_unli_23d7f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_unlisted", "contribution_points"],
                name="judge_profi_is_unli_d33ae9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["is_unlisted", "points"], name="judge_profi_is_unli_b95922_idx"
            ),
        ),
    ]
