# Generated by Django 4.2.27 on 2026-03-23 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0230_add_composite_indexes_for_user_list_sorting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="The group of problem, shown under Category in the problem list.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="judge.problemgroup",
                verbose_name="problem group",
            ),
        ),
    ]
