# Generated by Django 4.2.27 on 2026-04-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0233_contestproblem_courselessonquiz_is_result_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_shown_correctness",
            field=models.BooleanField(
                default=True,
                help_text="Whether per-question correctness (right/wrong) is shown after submission. Score is always shown.",
                verbose_name="Show Correctness",
            ),
        ),
    ]
