# Generated by Django 4.2.27 on 2026-04-20 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0234_quiz_is_shown_correctness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestquizattempt",
            name="max_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Maximum possible score",
                max_digits=10,
                verbose_name="max score",
            ),
        ),
        migrations.AlterField(
            model_name="bestquizattempt",
            name="score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Best score achieved",
                max_digits=10,
                verbose_name="score",
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="max_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Max Score",
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Score",
            ),
        ),
        migrations.AlterField(
            model_name="quizquestionassignment",
            name="points",
            field=models.IntegerField(
                default=1,
                help_text="Points for this question in this quiz (max 1000)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Points",
            ),
        ),
    ]
