# Generated by Django 4.2.29 on 2026-04-27 04:29

from django.db import migrations, models
import django.db.models.deletion
import judge.models.problem_attachment
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0235_quiz_points_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="is_shown_answer",
            field=models.BooleanField(
                default=False,
                help_text="Whether correct answers and explanations are shown to students after submission",
                verbose_name="Show Answers",
            ),
        ),
        migrations.CreateModel(
            name="ProblemAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=judge.utils.problem_data.ProblemDataStorage(),
                        upload_to=judge.models.problem_attachment.problem_attachment_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="judge.problem",
                        verbose_name="problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "problem attachment",
                "verbose_name_plural": "problem attachments",
                "ordering": ["order", "id"],
            },
        ),
    ]
