# Generated by Django 5.2.13 on 2026-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0238_alter_profile_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="format_config",
            field=models.JSONField(
                blank=True,
                help_text="A JSON object to serve as the configuration for the chosen contest format module. Leave empty to use None. Exact format depends on the contest format selected.",
                null=True,
                verbose_name="contest format configuration",
            ),
        ),
        migrations.AlterField(
            model_name="contestparticipation",
            name="format_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="contest format specific data"
            ),
        ),
        migrations.AlterField(
            model_name="contestparticipation",
            name="format_data_final",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="same as format_data, but including frozen results",
            ),
        ),
    ]
