# Generated by Django 5.2.13 on 2026-04-28 07:02

import judge.models.problem_attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0239_alter_contest_format_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemattachment",
            name="file",
            field=models.FileField(
                upload_to=judge.models.problem_attachment.problem_attachment_path,
                verbose_name="file",
            ),
        ),
    ]
