# Generated by Django 5.2.13 on 2026-04-30 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0240_alter_problemattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="banned_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bans the selected users from joining this contest.",
                to="judge.profile",
                verbose_name="Banned users",
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="key",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9]+$", "Contest id must be ^[a-z0-9]+$"
                    )
                ],
                verbose_name="contest id",
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="name",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="contest name"
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="banned_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bans the selected users from submitting to this problem.",
                to="judge.profile",
                verbose_name="Banned users",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="code",
            field=models.CharField(
                help_text="A short, unique code for the problem, used in the url after /problem/",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9]+$", "Problem code must be ^[a-z0-9]+$"
                    )
                ],
                verbose_name="problem code",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="The full name of the problem, as shown in the problem list.",
                max_length=150,
                verbose_name="problem name",
            ),
        ),
    ]
