# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0241_widen_contest_problem_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dynamic_effect",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("snowflakes", "Snowflakes"),
                    ("snow", "Snow"),
                    ("cherry_blossoms", "Cherry Blossoms"),
                    ("red_poinciana", "Red Poinciana"),
                    ("rain", "Rain"),
                    ("fireflies", "Fireflies"),
                    ("lunar_new_year", "Lunar New Year"),
                ],
                default="none",
                max_length=30,
                verbose_name="Dynamic effect",
            ),
        ),
    ]
