# Generated by Django 5.2.13 on 2026-05-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0242_alter_profile_dynamic_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="binary_data",
            field=models.BooleanField(
                blank=True,
                help_text="Skip newline normalisation on answer files. Required when the answer key or submission is binary (e.g. .npz / .npy / images).",
                null=True,
                verbose_name="binary answer data",
            ),
        ),
        migrations.AddField(
            model_name="problemdata",
            name="output_zip_size_mb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum size in megabytes of the user's submission zip for output-only problems. Defaults to 1 MB if unset.",
                null=True,
                verbose_name="output submission size limit (MB)",
            ),
        ),
    ]
