# Generated by Django 5.2.13 on 2026-05-22 21:43

import django.core.validators
import judge.models.problem_data
import judge.utils.problem_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0243_problemdata_binary_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="communication_manager",
            field=models.FileField(
                blank=True,
                help_text="Manager binary source for IOI-style Communication tasks. The manager runs as a separate sandboxed process and talks to the user's solution through FIFO pipes. testlib.h should be inlined into this file. Requires `communication_num_processes` >= 1.",
                null=True,
                storage=judge.utils.problem_data.ProblemDataStorage(),
                upload_to=judge.models.problem_data.problem_directory_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["cpp", "c"]
                    )
                ],
                verbose_name="communication manager",
            ),
        ),
        migrations.AddField(
            model_name="problemdata",
            name="communication_num_processes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How many independent copies of the user's solution to launch alongside the manager. Set to 1 for single-process callbacks (e.g. IOI Souvenirs); set to 2 for two-phase tasks (e.g. IOI Migrations). 0 means no communication.",
                null=True,
                verbose_name="communication num processes",
            ),
        ),
    ]
