# Generated by Django 5.2.13 on 2026-05-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0244_problemdata_communication_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemdata",
            name="checker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("floats", "Floats"),
                    ("floatsabs", "Floats (absolute)"),
                    ("floatsrel", "Floats (relative)"),
                    ("rstripped", "Non-trailing spaces"),
                    ("sorted", "Unordered"),
                    ("identical", "Byte identical"),
                    ("linecount", "Line-by-line"),
                    ("custom", "Custom checker (PY)"),
                    ("customcpp", "Custom checker (CPP)"),
                    ("interact", "Interactive"),
                    ("testlib", "Testlib"),
                    ("testlibcms", "Testlib (CMS / IOI)"),
                    ("interacttl", "Interactive (Testlib)"),
                    ("csv_accuracy", "CSV: accuracy"),
                    ("csv_rmse", "CSV: RMSE"),
                    ("csv_mae", "CSV: MAE"),
                    ("csv_f1", "CSV: F1 (macro)"),
                    ("csv_auc", "CSV: AUC (binary)"),
                    ("csv_logloss", "CSV: log loss"),
                ],
                max_length=20,
                verbose_name="checker",
            ),
        ),
        migrations.AlterField(
            model_name="problemtestcase",
            name="checker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("standard", "Standard"),
                    ("floats", "Floats"),
                    ("floatsabs", "Floats (absolute)"),
                    ("floatsrel", "Floats (relative)"),
                    ("rstripped", "Non-trailing spaces"),
                    ("sorted", "Unordered"),
                    ("identical", "Byte identical"),
                    ("linecount", "Line-by-line"),
                    ("custom", "Custom checker (PY)"),
                    ("customcpp", "Custom checker (CPP)"),
                    ("interact", "Interactive"),
                    ("testlib", "Testlib"),
                    ("testlibcms", "Testlib (CMS / IOI)"),
                    ("interacttl", "Interactive (Testlib)"),
                    ("csv_accuracy", "CSV: accuracy"),
                    ("csv_rmse", "CSV: RMSE"),
                    ("csv_mae", "CSV: MAE"),
                    ("csv_f1", "CSV: F1 (macro)"),
                    ("csv_auc", "CSV: AUC (binary)"),
                    ("csv_logloss", "CSV: log loss"),
                ],
                max_length=20,
                verbose_name="checker",
            ),
        ),
    ]
