# Generated by Django 5.2.13 on 2026-05-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0245_alter_problemdata_checker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemdata",
            name="is_communication",
            field=models.BooleanField(
                default=False,
                help_text="Tick to mark this as an IOI-style Communication task. The communication manager + num_processes fields below only apply when this is checked.",
                verbose_name="is communication",
            ),
        ),
    ]
