# Generated by Django 5.2.13 on 2026-05-23 01:41

import django.core.validators
import judge.models.problem_data
import judge.utils.problem_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0246_problemdata_is_communication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemdata",
            name="communication_manager",
            field=models.FileField(
                blank=True,
                help_text="Manager source. Runs sandboxed, talks to user via FIFO.",
                null=True,
                storage=judge.utils.problem_data.ProblemDataStorage(),
                upload_to=judge.models.problem_data.problem_directory_file,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["cpp", "c"]
                    )
                ],
                verbose_name="Manager",
            ),
        ),
        migrations.AlterField(
            model_name="problemdata",
            name="communication_num_processes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Copies of the user's solution to launch (1 for callbacks, 2+ for multi-phase).",
                null=True,
                verbose_name="Num processes",
            ),
        ),
        migrations.AlterField(
            model_name="problemdata",
            name="is_communication",
            field=models.BooleanField(
                default=False,
                help_text="IOI-style multi-process task with a manager.",
                verbose_name="Is communication",
            ),
        ),
    ]
