# Generated by Django 5.2.13 on 2026-05-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0247_alter_problemdata_communication_manager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemtestcase",
            name="batch_scoring",
            field=models.CharField(
                choices=[("sum", "Sum"), ("min", "Min")],
                default="sum",
                help_text="How per-case scores aggregate into the batch score. Only applies to Batch start (S) rows. Sum: Σ(case_points) — with [0,…,0,1] weights this is all-or-nothing. Min: min(case_fraction) × batch_points — use [1,…,1] weights.",
                max_length=20,
                verbose_name="batch scoring",
            ),
        ),
    ]
