# Generated by Django 5.2.13 on 2026-05-24 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0248_problemtestcase_batch_scoring"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemDuplicateMergeHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_problem_id_snapshot", models.PositiveIntegerField()),
                ("target_problem_id_snapshot", models.PositiveIntegerField()),
                ("source_code", models.CharField(max_length=30)),
                ("target_code", models.CharField(max_length=30)),
                ("source_name", models.CharField(max_length=150)),
                ("target_name", models.CharField(max_length=150)),
                ("merged_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("conflicts", models.JSONField(blank=True, default=dict)),
                (
                    "merged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="judge.problem",
                    ),
                ),
                (
                    "target_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="judge.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["-merged_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemDuplicateReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_score", models.FloatField(default=0.97)),
                ("limit", models.PositiveIntegerField(default=100)),
                ("neighbors", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("S", "Success"), ("F", "Failed")],
                        db_index=True,
                        default="P",
                        max_length=1,
                    ),
                ),
                ("task_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("candidate_count", models.PositiveIntegerField(default=0)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemDuplicateCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_problem_id_snapshot", models.PositiveIntegerField()),
                ("target_problem_id_snapshot", models.PositiveIntegerField()),
                ("source_code", models.CharField(max_length=30)),
                ("target_code", models.CharField(max_length=30)),
                ("source_name", models.CharField(max_length=150)),
                ("target_name", models.CharField(max_length=150)),
                ("source_submission_count", models.PositiveIntegerField(default=0)),
                ("target_submission_count", models.PositiveIntegerField(default=0)),
                ("score", models.FloatField(db_index=True)),
                (
                    "source_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="judge.problem",
                    ),
                ),
                (
                    "target_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="judge.problem",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="judge.problemduplicatereport",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "source_code", "target_code"],
            },
        ),
        migrations.AddIndex(
            model_name="problemduplicatereport",
            index=models.Index(
                fields=["status", "-started_at"], name="judge_probl_status_308f89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemduplicatereport",
            index=models.Index(
                fields=["min_score", "limit", "neighbors", "-started_at"],
                name="judge_probl_min_sco_e1dd43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="problemduplicatecandidate",
            index=models.Index(
                fields=["report", "-score"], name="judge_probl_report__f055fd_idx"
            ),
        ),
    ]
