# Generated by Django 5.2.13 on 2026-05-24 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0249_problemduplicatemergehistory_problemduplicatereport_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problemduplicatemergehistory",
            options={"ordering": ["-requested_at"]},
        ),
        migrations.AddField(
            model_name="problemduplicatemergehistory",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="problemduplicatemergehistory",
            name="requested_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="problemduplicatemergehistory",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problemduplicatemergehistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("R", "Running"),
                    ("S", "Success"),
                    ("F", "Failed"),
                ],
                db_index=True,
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="problemduplicatemergehistory",
            name="task_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="problemduplicatemergehistory",
            name="merged_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
