# Generated by Django 5.2.13 on 2026-05-24 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0250_alter_problemduplicatemergehistory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="problemduplicatecandidate",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problemduplicatecandidate",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="problemduplicatecandidate",
            name="status",
            field=models.CharField(
                choices=[("O", "Open"), ("F", "False positive")],
                db_index=True,
                default="O",
                max_length=1,
            ),
        ),
    ]
