# Generated by Django 5.2.13 on 2026-05-24 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0251_problemduplicatecandidate_reviewed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemDuplicateReviewHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("merge_queued", "Merge queued"),
                            ("merge_running", "Merge running"),
                            ("merged", "Merged"),
                            ("merge_failed", "Merge failed"),
                            ("marked_not_duplicate", "Marked not duplicated"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("source_code", models.CharField(max_length=30)),
                ("target_code", models.CharField(max_length=30)),
                (
                    "source_problem_id_snapshot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "target_problem_id_snapshot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
