# Generated by Django 5.2.13 on 2026-05-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0252_problemduplicatereviewhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": (
                    ("test_site", "Shows in-progress development stuff"),
                    ("totp", "Edit TOTP settings"),
                    ("use_ai_features", "Use AI features"),
                ),
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
    ]
