# Generated by Django 5.2.13 on 2026-06-01 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0253_profile_use_ai_features_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemReviewCheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_id", models.CharField(max_length=64, verbose_name="check id")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("S", "Pass"),
                            ("F", "Fail"),
                            ("K", "Skipped"),
                            ("E", "Error"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "details_json",
                    models.JSONField(blank=True, default=dict, verbose_name="details"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
            ],
            options={
                "verbose_name": "problem review check result",
                "verbose_name_plural": "problem review check results",
                "ordering": ["run", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProblemReviewRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "Running"), ("D", "Done"), ("E", "Error")],
                        db_index=True,
                        default="R",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "input_hash",
                    models.CharField(
                        help_text="sha256 of problem state used by dirty-check",
                        max_length=64,
                        verbose_name="input hash",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
                (
                    "summary_report",
                    models.TextField(blank=True, verbose_name="summary report"),
                ),
            ],
            options={
                "verbose_name": "problem review run",
                "verbose_name_plural": "problem review runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemReviewSubmissionTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Main AC"),
                            ("S", "Subtask-targeted"),
                            ("B", "Brute force / suboptimal"),
                        ],
                        help_text="Optional — the LLM will classify if not set.",
                        max_length=1,
                        null=True,
                        verbose_name="kind",
                    ),
                ),
                (
                    "target_subtask",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-indexed. Required when kind=Subtask.",
                        null=True,
                        verbose_name="target subtask",
                    ),
                ),
                (
                    "claimed_complexity",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="claimed complexity"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="author note")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "problem review submission tag",
                "verbose_name_plural": "problem review submission tags",
                "ordering": ["submission__problem", "kind", "target_subtask"],
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("add_blog", "Added a post"),
                    ("added_to_group", "You are added to a group"),
                    ("comment", "You have a new comment"),
                    ("delete_blog", "Deleted a post"),
                    ("reject_blog", "Rejected a post"),
                    ("approve_blog", "Approved a post"),
                    ("edit_blog", "Edited a post"),
                    ("hide_comment", "Your comment was hidden"),
                    ("mention", "Mentioned you"),
                    ("organization", "Organization"),
                    ("problem", "Problem"),
                    ("reply", "Replied you"),
                    ("ticket", "Ticket"),
                    ("problem_public", "Problem visibility changed"),
                    ("problem_private", "Problem visibility changed"),
                    ("quiz_needs_grading", "Quiz answer needs grading"),
                    ("public_request_new", "New public request"),
                    ("public_request_approved", "Public request approved"),
                    ("public_request_rejected", "Public request rejected"),
                    ("public_request_review_done", "Auto-review completed"),
                    ("public_request_review_error", "Auto-review error"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="problemreviewrun",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_runs",
                to="judge.problem",
                verbose_name="problem",
            ),
        ),
        migrations.AddField(
            model_name="problemreviewrun",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="judge.problemreviewrun",
                verbose_name="superseded by",
            ),
        ),
        migrations.AddField(
            model_name="problemreviewrun",
            name="triggered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_review_runs",
                to="judge.profile",
                verbose_name="triggered by",
            ),
        ),
        migrations.AddField(
            model_name="problemreviewcheckresult",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_results",
                to="judge.problemreviewrun",
                verbose_name="review run",
            ),
        ),
        migrations.AddField(
            model_name="problemreviewsubmissiontag",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_tag",
                to="judge.submission",
                verbose_name="submission",
            ),
        ),
        migrations.AddField(
            model_name="problemreviewsubmissiontag",
            name="tagged_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_tags",
                to="judge.profile",
                verbose_name="tagged by",
            ),
        ),
        migrations.AddIndex(
            model_name="problemreviewrun",
            index=models.Index(
                fields=["problem", "superseded_by", "-started_at"],
                name="prob_review_run_latest_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="problemreviewcheckresult",
            unique_together={("run", "check_id")},
        ),
    ]
