# Generated by Django 5.2.13 on 2026-06-08 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0254_add_problem_review_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestPublicRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("A", "Approved"),
                            ("R", "Rejected"),
                        ],
                        db_index=True,
                        default="P",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="admin feedback"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "contest public request",
                "verbose_name_plural": "contest public requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContestReviewCheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_id", models.CharField(max_length=64, verbose_name="check id")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("S", "Pass"),
                            ("F", "Fail"),
                            ("W", "Warning"),
                            ("K", "Skipped"),
                            ("E", "Error"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "details_json",
                    models.JSONField(blank=True, default=dict, verbose_name="details"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
            ],
            options={
                "verbose_name": "contest review check result",
                "verbose_name_plural": "contest review check results",
                "ordering": ["run", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContestReviewRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "Running"), ("D", "Done"), ("E", "Error")],
                        db_index=True,
                        default="R",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "input_hash",
                    models.CharField(
                        help_text="sha256 of contest state used by dirty-check",
                        max_length=64,
                        verbose_name="input hash",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="finished at"
                    ),
                ),
                (
                    "summary_report",
                    models.TextField(blank=True, verbose_name="summary report"),
                ),
                (
                    "force_refresh_problems",
                    models.BooleanField(
                        default=False, verbose_name="force refresh per-problem reviews"
                    ),
                ),
            ],
            options={
                "verbose_name": "contest review run",
                "verbose_name_plural": "contest review runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("add_blog", "Added a post"),
                    ("added_to_group", "You are added to a group"),
                    ("comment", "You have a new comment"),
                    ("delete_blog", "Deleted a post"),
                    ("reject_blog", "Rejected a post"),
                    ("approve_blog", "Approved a post"),
                    ("edit_blog", "Edited a post"),
                    ("hide_comment", "Your comment was hidden"),
                    ("mention", "Mentioned you"),
                    ("organization", "Organization"),
                    ("problem", "Problem"),
                    ("reply", "Replied you"),
                    ("ticket", "Ticket"),
                    ("problem_public", "Problem visibility changed"),
                    ("problem_private", "Problem visibility changed"),
                    ("quiz_needs_grading", "Quiz answer needs grading"),
                    ("public_request_new", "New public request"),
                    ("public_request_approved", "Public request approved"),
                    ("public_request_rejected", "Public request rejected"),
                    ("public_request_review_done", "Auto-review completed"),
                    ("public_request_review_error", "Auto-review error"),
                    ("contest_public_request_new", "New contest public request"),
                    (
                        "contest_public_request_approved",
                        "Contest public request approved",
                    ),
                    (
                        "contest_public_request_rejected",
                        "Contest public request rejected",
                    ),
                    (
                        "contest_public_request_review_done",
                        "Contest auto-review completed",
                    ),
                    (
                        "contest_public_request_review_error",
                        "Contest auto-review error",
                    ),
                ],
                db_index=True,
                max_length=50,
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="contestpublicrequest",
            name="contest",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_request",
                to="judge.contest",
                verbose_name="contest",
            ),
        ),
        migrations.AddField(
            model_name="contestpublicrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contest_public_requests",
                to="judge.profile",
                verbose_name="requested by",
            ),
        ),
        migrations.AddField(
            model_name="contestpublicrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_contest_public_requests",
                to="judge.profile",
                verbose_name="reviewed by",
            ),
        ),
        migrations.AddField(
            model_name="contestreviewrun",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_runs",
                to="judge.contest",
                verbose_name="contest",
            ),
        ),
        migrations.AddField(
            model_name="contestreviewrun",
            name="problem_review_runs",
            field=models.ManyToManyField(
                blank=True,
                related_name="consulted_by_contest_reviews",
                to="judge.problemreviewrun",
                verbose_name="consulted problem review runs",
            ),
        ),
        migrations.AddField(
            model_name="contestreviewrun",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="judge.contestreviewrun",
                verbose_name="superseded by",
            ),
        ),
        migrations.AddField(
            model_name="contestreviewrun",
            name="triggered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_contest_review_runs",
                to="judge.profile",
                verbose_name="triggered by",
            ),
        ),
        migrations.AddField(
            model_name="contestreviewcheckresult",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_results",
                to="judge.contestreviewrun",
                verbose_name="review run",
            ),
        ),
        migrations.AddIndex(
            model_name="contestreviewrun",
            index=models.Index(
                fields=["contest", "superseded_by", "-started_at"],
                name="con_review_run_latest_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestreviewcheckresult",
            unique_together={("run", "check_id")},
        ),
    ]
