# Generated by Django 5.2.13 on 2026-06-14 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0255_contest_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestproblemclarification",
            name="contest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="judge.contest",
                verbose_name="clarified contest",
            ),
        ),
        migrations.AlterField(
            model_name="contestproblemclarification",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="judge.contestproblem",
                verbose_name="clarified problem",
            ),
        ),
    ]
