# Generated by Django 5.2.13 on 2026-06-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0256_contest_wide_clarifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("add_blog", "Added a post"),
                    ("added_to_group", "You are added to a group"),
                    ("comment", "You have a new comment"),
                    ("delete_blog", "Deleted a post"),
                    ("reject_blog", "Rejected a post"),
                    ("approve_blog", "Approved a post"),
                    ("edit_blog", "Edited a post"),
                    ("hide_comment", "Your comment was hidden"),
                    ("mention", "Mentioned you"),
                    ("organization", "Organization"),
                    ("problem", "Problem"),
                    ("reply", "Replied you"),
                    ("ticket", "Ticket"),
                    ("problem_public", "Problem visibility changed"),
                    ("problem_private", "Problem visibility changed"),
                    ("quiz_needs_grading", "Quiz answer needs grading"),
                    ("public_request_new", "New public request"),
                    ("public_request_approved", "Public request approved"),
                    ("public_request_rejected", "Public request rejected"),
                    ("public_request_review_done", "Auto-review completed"),
                    ("public_request_review_error", "Auto-review error"),
                    ("contest_public_request_new", "New contest public request"),
                    (
                        "contest_public_request_approved",
                        "Contest public request approved",
                    ),
                    (
                        "contest_public_request_rejected",
                        "Contest public request rejected",
                    ),
                    (
                        "contest_public_request_review_done",
                        "Contest auto-review completed",
                    ),
                    (
                        "contest_public_request_review_error",
                        "Contest auto-review error",
                    ),
                    ("review_comment", "New review comment"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="category",
            ),
        ),
    ]
