# Generated by Django 5.2.13 on 2026-06-22 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0258_contestsubmission_hidden_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontest",
            name="points",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="points",
            ),
        ),
        migrations.AlterField(
            model_name="courselesson",
            name="points",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="points",
            ),
        ),
        migrations.AlterField(
            model_name="courselessonproblem",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="score",
            ),
        ),
        migrations.AlterField(
            model_name="courselessonquiz",
            name="max_attempts",
            field=models.IntegerField(
                default=0,
                help_text="0 for unlimited attempts; maximum 100",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Max Attempts",
            ),
        ),
        migrations.AlterField(
            model_name="courselessonquiz",
            name="points",
            field=models.IntegerField(
                default=0,
                help_text="Points awarded in lesson for completing quiz (max 1000)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Lesson Points",
            ),
        ),
        migrations.AlterField(
            model_name="problemdata",
            name="communication_num_processes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Copies of the user's solution to launch (1 for callbacks, 2+ for multi-phase).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(16),
                ],
                verbose_name="Num processes",
            ),
        ),
        migrations.AlterField(
            model_name="problemdata",
            name="output_zip_size_mb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum size in megabytes of the user's submission zip for output-only problems. Defaults to 1 MB if unset.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="output submission size limit (MB)",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="time_limit",
            field=models.IntegerField(
                default=0,
                help_text="0 for no time limit; maximum 10080 minutes",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10080),
                ],
                verbose_name="Time Limit (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="time_limit_minutes",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10080),
                ],
                verbose_name="Time Limit (minutes)",
            ),
        ),
    ]
