# Generated by Django 5.2.13 on 2026-07-21 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0260_profile_temporary_mute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsernameModerationCase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, verbose_name="username")),
                (
                    "normalized_username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="normalized username"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("R", "Reviewed")],
                        db_index=True,
                        default="P",
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("allow", "Allow"),
                            ("review", "Needs review"),
                            ("block", "Block"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="decision",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("gambling", "Gambling"),
                            ("offensive", "Offensive"),
                            ("obscene", "Obscene"),
                            ("impersonation", "Impersonation"),
                            ("spam", "Spam"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, null=True, verbose_name="confidence"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="raw response"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("audit", "Audit"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        default="registration",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "public_identity_hidden",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Show this account as Disabled user to normal visitors.",
                        verbose_name="public identity hidden",
                    ),
                ),
                (
                    "is_automated",
                    models.BooleanField(default=False, verbose_name="automated"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decided at"
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="username_moderation_actions",
                        to="judge.profile",
                        verbose_name="moderator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="username_moderation_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "username moderation case",
                "verbose_name_plural": "username moderation cases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "decision", "created_at"],
                        name="judge_usern_status_f9f309_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="judge_usern_user_id_b7ec87_idx",
                    ),
                    models.Index(
                        fields=["category", "created_at"],
                        name="judge_usern_categor_2c437d_idx",
                    ),
                ],
            },
        ),
    ]
