# Generated by Django 5.2.13 on 2026-07-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0261_usernamemoderationcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("add_blog", "Added a post"),
                    ("added_to_group", "You are added to a group"),
                    ("comment", "You have a new comment"),
                    ("delete_blog", "Deleted a post"),
                    ("reject_blog", "Rejected a post"),
                    ("approve_blog", "Approved a post"),
                    ("edit_blog", "Edited a post"),
                    ("hide_comment", "Your comment was hidden"),
                    ("mention", "Mentioned you"),
                    ("organization", "Organization"),
                    ("problem", "Problem"),
                    ("reply", "Replied you"),
                    ("ticket", "Ticket"),
                    ("problem_public", "Problem visibility changed"),
                    ("problem_private", "Problem visibility changed"),
                    ("quiz_needs_grading", "Quiz answer needs grading"),
                    ("public_request_new", "New public request"),
                    ("public_request_approved", "Public request approved"),
                    ("public_request_rejected", "Public request rejected"),
                    ("public_request_review_done", "Auto-review completed"),
                    ("public_request_review_error", "Auto-review error"),
                    ("contest_public_request_new", "New contest public request"),
                    (
                        "contest_public_request_approved",
                        "Contest public request approved",
                    ),
                    (
                        "contest_public_request_rejected",
                        "Contest public request rejected",
                    ),
                    (
                        "contest_public_request_review_done",
                        "Contest auto-review completed",
                    ),
                    (
                        "contest_public_request_review_error",
                        "Contest auto-review error",
                    ),
                    ("review_comment", "New review comment"),
                    ("chat_mute", "Chat muted"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="category",
            ),
        ),
        migrations.CreateModel(
            name="CommentModerationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("keep", "Keep"),
                            ("hide", "Hide Comment"),
                            ("review", "Needs Review"),
                            ("mute_temp", "Temporarily Mute User"),
                            ("mute_perm", "Permanently Mute User"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("is_automated", models.BooleanField(default=False)),
                ("mute_until", models.DateTimeField(blank=True, null=True)),
                (
                    "mute_duration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="judge.comment",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_moderation_actions",
                        to="judge.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment moderation log",
                "verbose_name_plural": "comment moderation logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["comment", "content_hash"],
                        name="judge_comme_comment_5f0184_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="judge_comme_action_7bb78d_idx",
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="mute",
            field=models.BooleanField(
                default=False,
                help_text="Prevents the user from using chat and comments.",
                verbose_name="chat mute",
            ),
        ),
    ]
