# Generated by Django 5.2.13 on 2026-08-02

from django.db import migrations, models
from django.db.models import Count, Max


def deduplicate_organization_profiles(apps, schema_editor):
    OrganizationProfile = apps.get_model("judge", "OrganizationProfile")

    duplicate_groups = (
        OrganizationProfile.objects.values("profile_id", "organization_id")
        .annotate(row_count=Count("id"), latest_visit_time=Max("last_visit_time"))
        .filter(row_count__gt=1)
    )

    for group in duplicate_groups.iterator():
        visit_ids = list(
            OrganizationProfile.objects.filter(
                profile_id=group["profile_id"],
                organization_id=group["organization_id"],
            )
            .order_by("-last_visit_time", "-id")
            .values_list("id", flat=True)
        )
        if not visit_ids:
            continue

        OrganizationProfile.objects.filter(id=visit_ids[0]).update(
            last_visit_time=group["latest_visit_time"]
        )
        OrganizationProfile.objects.filter(id__in=visit_ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0262_alter_notification_category_commentmoderationlog"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_organization_profiles,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="organizationprofile",
            constraint=models.UniqueConstraint(
                fields=("profile", "organization"),
                name="unique_organization_profile_visit",
            ),
        ),
    ]
