# Generated by Django 5.2.13 on 2026-08-07 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0263_unique_organization_profile_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestproblem",
            name="initial_ac_score",
            field=models.FloatField(
                blank=True,
                help_text="Score for an AC at contest start. Leave blank to use round(10 / 3 * points).",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="initial AC score",
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="format_name",
            field=models.CharField(
                choices=[
                    ("atcoder", "AtCoder"),
                    ("codeforces", "Codeforces"),
                    ("default", "Default"),
                    ("ecoo", "ECOO"),
                    ("icpc", "ICPC"),
                    ("ioi", "IOI"),
                    ("ioi16", "New IOI"),
                    ("ultimate", "Ultimate"),
                ],
                default="default",
                help_text="The contest format module to use.",
                max_length=32,
                verbose_name="contest format",
            ),
        ),
    ]
