# Generated by Django 5.2.13 on 2026-08-13 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0264_contestproblem_initial_ac_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestMetric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="time",
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="URL name",
                    ),
                ),
                ("path", models.TextField(blank=True, verbose_name="path")),
                ("full_url", models.TextField(blank=True, verbose_name="full URL")),
                (
                    "method",
                    models.CharField(blank=True, max_length=10, verbose_name="method"),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="status code"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        verbose_name="username",
                    ),
                ),
                (
                    "response_time_ms",
                    models.FloatField(db_index=True, verbose_name="response time (ms)"),
                ),
                (
                    "db_query_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="database query count"
                    ),
                ),
                (
                    "db_time_ms",
                    models.FloatField(
                        blank=True, null=True, verbose_name="database time (ms)"
                    ),
                ),
                (
                    "profiler",
                    models.JSONField(blank=True, default=dict, verbose_name="profiler"),
                ),
            ],
            options={
                "verbose_name": "request metric",
                "verbose_name_plural": "request metrics",
                "ordering": ["-time"],
                "indexes": [
                    models.Index(
                        fields=["url_name", "-time"], name="req_metric_url_time"
                    ),
                    models.Index(
                        fields=["response_time_ms"], name="req_metric_resp_time"
                    ),
                    models.Index(fields=["time"], name="req_metric_time"),
                ],
            },
        ),
    ]
