# Generated by Django 5.2.13 on 2026-08-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0265_requestmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmetric",
            name="is_authenticated",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="authenticated"
            ),
        ),
    ]
