# Generated by Django 5.2.13 on 2026-08-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0266_requestmetric_is_authenticated"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmetric",
            name="cache_call_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="cache call count"
            ),
        ),
        migrations.AddField(
            model_name="requestmetric",
            name="cache_time_ms",
            field=models.FloatField(
                blank=True, null=True, verbose_name="cache time (ms)"
            ),
        ),
    ]
