# Generated by Django 5.2.13 on 2026-08-26 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0269_remove_submissiontestcase_result_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usernamemoderationcase",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "profile moderation case",
                "verbose_name_plural": "profile moderation cases",
            },
        ),
        migrations.AddField(
            model_name="usernamemoderationcase",
            name="target",
            field=models.CharField(
                choices=[("username", "Username"), ("about", "Self-description")],
                db_index=True,
                default="username",
                max_length=20,
                verbose_name="target",
            ),
        ),
        migrations.AddField(
            model_name="usernamemoderationcase",
            name="value_snapshot",
            field=models.TextField(
                blank=True, null=True, verbose_name="value snapshot"
            ),
        ),
        migrations.AlterField(
            model_name="usernamemoderationcase",
            name="source",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("profile_edit", "Profile edit"),
                    ("audit", "Audit"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="registration",
                max_length=20,
                verbose_name="source",
            ),
        ),
        migrations.AddIndex(
            model_name="usernamemoderationcase",
            index=models.Index(
                fields=["target", "status", "decision", "created_at"],
                name="judge_usern_target_4f6b29_idx",
            ),
        ),
    ]
