# Generated by Django 5.2.13 on 2026-08-31 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0270_alter_usernamemoderationcase_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="time",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        verbose_name="username",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="feature",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="bot name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "duration_ms",
                    models.FloatField(
                        blank=True, null=True, verbose_name="duration (ms)"
                    ),
                ),
                (
                    "input_chars",
                    models.PositiveIntegerField(default=0, verbose_name="input chars"),
                ),
                (
                    "output_chars",
                    models.PositiveIntegerField(default=0, verbose_name="output chars"),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="message count"
                    ),
                ),
                (
                    "attachment_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="attachment count"
                    ),
                ),
                (
                    "tool_count",
                    models.PositiveIntegerField(default=0, verbose_name="tool count"),
                ),
                ("error", models.TextField(blank=True, verbose_name="error")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI usage log",
                "verbose_name_plural": "AI usage logs",
                "ordering": ["-time"],
                "indexes": [
                    models.Index(
                        fields=["feature", "-time"], name="ai_usage_feature_time"
                    ),
                    models.Index(
                        fields=["username", "-time"], name="ai_usage_user_time"
                    ),
                    models.Index(
                        fields=["bot_name", "-time"], name="ai_usage_bot_time"
                    ),
                    models.Index(
                        fields=["status", "-time"], name="ai_usage_status_time"
                    ),
                ],
            },
        ),
    ]
