# Generated by Django 5.2.13 on 2026-09-10 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0272_add_room_membership_notification_category"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bestquizattempt",
            name="judge_bestq_user_id_134b87_idx",
        ),
        migrations.RemoveIndex(
            model_name="bestsubmission",
            name="judge_bests_user_id_dc617a_idx",
        ),
        migrations.RemoveIndex(
            model_name="block",
            name="blocker_idx",
        ),
        migrations.RemoveIndex(
            model_name="bookmark",
            name="judge_bookm_content_964329_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="judge_notif_time_94feb0_idx",
        ),
        migrations.RemoveIndex(
            model_name="pagevote",
            name="judge_pagev_content_ed8899_idx",
        ),
        migrations.RemoveIndex(
            model_name="requestmetric",
            name="req_metric_resp_time",
        ),
        migrations.RemoveIndex(
            model_name="requestmetric",
            name="req_metric_time",
        ),
        migrations.AlterField(
            model_name="aiusagelog",
            name="bot_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="bot name"),
        ),
        migrations.AlterField(
            model_name="aiusagelog",
            name="feature",
            field=models.CharField(blank=True, max_length=100, verbose_name="feature"),
        ),
        migrations.AlterField(
            model_name="contestparticipation",
            name="score",
            field=models.FloatField(default=0, verbose_name="score"),
        ),
        migrations.AlterField(
            model_name="contestproblem",
            name="order",
            field=models.PositiveIntegerField(verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("add_blog", "Added a post"),
                    ("added_to_group", "You are added to a group"),
                    ("comment", "You have a new comment"),
                    ("delete_blog", "Deleted a post"),
                    ("reject_blog", "Rejected a post"),
                    ("approve_blog", "Approved a post"),
                    ("edit_blog", "Edited a post"),
                    ("hide_comment", "Your comment was hidden"),
                    ("mention", "Mentioned you"),
                    ("organization", "Organization"),
                    ("problem", "Problem"),
                    ("reply", "Replied you"),
                    ("ticket", "Ticket"),
                    ("problem_public", "Problem visibility changed"),
                    ("problem_private", "Problem visibility changed"),
                    ("quiz_needs_grading", "Quiz answer needs grading"),
                    ("public_request_new", "New public request"),
                    ("public_request_approved", "Public request approved"),
                    ("public_request_rejected", "Public request rejected"),
                    ("public_request_review_done", "Auto-review completed"),
                    ("public_request_review_error", "Auto-review error"),
                    ("contest_public_request_new", "New contest public request"),
                    (
                        "contest_public_request_approved",
                        "Contest public request approved",
                    ),
                    (
                        "contest_public_request_rejected",
                        "Contest public request rejected",
                    ),
                    (
                        "contest_public_request_review_done",
                        "Contest auto-review completed",
                    ),
                    (
                        "contest_public_request_review_error",
                        "Contest auto-review error",
                    ),
                    ("review_comment", "New review comment"),
                    ("chat_mute", "Chat moderation"),
                    ("room_membership", "Room membership"),
                ],
                max_length=50,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="last_visit_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last visit"
            ),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="profile",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_visit",
                to="judge.profile",
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="problemduplicatereport",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Success"), ("F", "Failed")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mute_until",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, the mute expires at this time.",
                null=True,
                verbose_name="muted until",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="performance_points",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="points",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="problem_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="requestmetric",
            name="is_authenticated",
            field=models.BooleanField(default=False, verbose_name="authenticated"),
        ),
        migrations.AlterField(
            model_name="requestmetric",
            name="username",
            field=models.CharField(blank=True, max_length=150, verbose_name="username"),
        ),
        migrations.AlterField(
            model_name="usernamemoderationcase",
            name="category",
            field=models.CharField(
                choices=[
                    ("safe", "Safe"),
                    ("gambling", "Gambling"),
                    ("offensive", "Offensive"),
                    ("obscene", "Obscene"),
                    ("impersonation", "Impersonation"),
                    ("spam", "Spam"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="usernamemoderationcase",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("R", "Reviewed")],
                default="P",
                max_length=1,
                verbose_name="status",
            ),
        ),
    ]
