# Generated by Django 5.2.13 on 2026-09-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "judge",
            "0273_remove_bestquizattempt_judge_bestq_user_id_134b87_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="time",
            field=models.FloatField(null=True, verbose_name="execution time"),
        ),
    ]
