# Generated by Django 5.2.13 on 2026-09-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0274_remove_submission_time_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="deadline_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="deadline_initialized",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="effective_end_time",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["is_submitted", "deadline_at"], name="quiz_attempt_expiry_idx"
            ),
        ),
    ]
