# Generated by Django 5.2.13 on 2026-09-13 06:15

"""Unify TF storage without regrading existing attempts.

Deploy with a database backup and web/worker writers stopped; reload open quiz
pages after deployment. Conversion discards old choice IDs, so rollback requires
restoring the database backup together with the old application release.
"""

import json
import unicodedata

from django.db import migrations, models


def truth_value(value):
    if not isinstance(value, str):
        return None
    token = unicodedata.normalize("NFC", value).strip().strip("*_`").strip().casefold()
    return {"true": True, "false": False, "đúng": True, "sai": False}.get(token)


def conversion_plan(question):
    config = question.correct_answers
    if isinstance(config, dict) and isinstance(config.get("answers"), dict):
        return None  # Already in the statement format; preserve custom tables.
    prefix = f"TF question {question.pk}"
    choices = question.choices
    if not isinstance(choices, list) or len(choices) != 2:
        raise ValueError(f"{prefix}: expected two old True/False choices")
    mapping = {}
    for choice in choices:
        if not isinstance(choice, dict) or not isinstance(choice.get("id"), str):
            raise ValueError(f"{prefix}: invalid choice ID")
        choice_id = choice["id"]
        if not choice_id.strip() or choice_id in mapping:
            raise ValueError(f"{prefix}: empty or duplicate choice ID")
        by_id, by_label = truth_value(choice_id), truth_value(choice.get("text"))
        if by_id is not None and by_label is not None and by_id != by_label:
            raise ValueError(f"{prefix}: conflicting True/False ID and label")
        value = by_label if by_label is not None else by_id
        if value is None:
            raise ValueError(
                f"{prefix}: ambiguous True/False choice; resolve before migrating"
            )
        mapping[choice_id] = value
    if set(mapping.values()) != {True, False}:
        raise ValueError(f"{prefix}: choices must represent both True and False")
    key = config.get("answers") if isinstance(config, dict) else None
    if not isinstance(key, str) or key not in mapping:
        raise ValueError(f"{prefix}: missing or unknown correct choice ID")
    if not isinstance(question.content, str) or not question.content.strip():
        raise ValueError(f"{prefix}: missing statement text")
    return mapping


def converted_response(answer_id, value, mapping):
    if value is None or (isinstance(value, str) and not value.strip()):
        return "{}"
    if not isinstance(value, str) or value not in mapping:
        raise ValueError(
            f"TF answer {answer_id}: unknown saved choice ID; resolve before migrating"
        )
    return json.dumps({"A": mapping[value]}, sort_keys=True)


def audit(apps, database):
    Question = apps.get_model("judge", "QuizQuestion")
    Answer = apps.get_model("judge", "QuizAnswer")
    plans = []
    for question in (
        Question.objects.using(database).filter(question_type="TF").order_by("pk")
    ):
        mapping = conversion_plan(question)
        if mapping is not None:
            plans.append((question, mapping))
    mappings = {question.pk: mapping for question, mapping in plans}
    count = 0
    for answer_id, question_id, value in (
        Answer.objects.using(database)
        .filter(question_id__in=mappings)
        .values_list("pk", "question_id", "answer")
        .iterator(chunk_size=2000)
    ):
        converted_response(answer_id, value, mappings[question_id])
        count += 1
    return plans, count


def forwards(apps, schema_editor):
    """Run with web/worker writers stopped. RunPython provides one atomic transaction."""
    database = schema_editor.connection.alias
    Question = apps.get_model("judge", "QuizQuestion")
    Answer = apps.get_model("judge", "QuizAnswer")
    # Validate everything before the first write, including unanswered/manual answers.
    plans, _ = audit(apps, database)
    mappings = {question.pk: mapping for question, mapping in plans}
    pending = []
    for answer_id, question_id, value in (
        Answer.objects.using(database)
        .filter(question_id__in=mappings)
        .values_list("pk", "question_id", "answer")
        .iterator(chunk_size=2000)
    ):
        pending.append(
            Answer(
                pk=answer_id,
                answer=converted_response(answer_id, value, mappings[question_id]),
            )
        )
        if len(pending) == 1000:
            Answer.objects.using(database).bulk_update(
                pending, ["answer"], batch_size=1000
            )
            pending.clear()
    if pending:
        Answer.objects.using(database).bulk_update(pending, ["answer"], batch_size=1000)
    questions = []
    for question, mapping in plans:
        question.choices = [{"id": "A", "text": question.content}]
        question.correct_answers = {
            **question.correct_answers,
            "answers": {"A": mapping[question.correct_answers["answers"]]},
        }
        question.content = ""
        question.multiple_true_false_score_table = [0, 100]
        questions.append(question)
    if questions:
        Question.objects.using(database).bulk_update(
            questions,
            [
                "choices",
                "correct_answers",
                "content",
                "multiple_true_false_score_table",
            ],
            batch_size=1000,
        )


def preflight(apps, schema_editor):
    # MariaDB cannot roll back AddField. Reject ambiguous data before any DDL.
    audit(apps, schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0275_quiz_attempt_deadlines"),
    ]

    operations = [
        migrations.RunPython(preflight, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="quizquestion",
            name="multiple_true_false_score_table",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Percentage awarded for each number of correctly evaluated statements",
                verbose_name="True/False Score Table",
            ),
        ),
        migrations.RunPython(forwards, atomic=True),
    ]
