# Generated by Django 5.2.13 on 2026-09-13 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0276_unify_true_false"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialSchool",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="official_school",
                        serialize=False,
                        to="judge.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Enrollment enabled"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_schools",
                        to="judge.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Official school",
                "verbose_name_plural": "Official schools",
            },
        ),
    ]
