# Generated by Django 2.2.12 on 2020-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
    ]
