# Generated by Django 2.2.12 on 2020-05-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_box', '0002_message_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='hidden',
            field=models.BooleanField(default=True, verbose_name='is hidden'),
        ),
    ]
