# Generated by Django 2.2.17 on 2021-11-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0116_auto_20211011_0645'),
        ('chat_box', '0007_auto_20211112_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ignore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_users', models.ManyToManyField(to='judge.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_chat_users', to='judge.Profile', verbose_name='user')),
            ],
        ),
    ]
