# Generated by Django 2.2.25 on 2022-06-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0008_ignore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ignore",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ignored_chat_users",
                to="judge.Profile",
                verbose_name="user",
            ),
        ),
    ]
