# Generated by Django 3.2.18 on 2023-03-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("judge", "0154_add_submission_indexes"),
        ("chat_box", "0011_alter_message_hidden"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("-id",),
                "verbose_name": "message",
                "verbose_name_plural": "messages",
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="is hidden"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["hidden", "room", "-id"], name="chat_box_me_hidden_b2307a_idx"
            ),
        ),
    ]
