# Generated by Django 3.2.18 on 2023-08-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0012_auto_20230308_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="posted time"
            ),
        ),
    ]
