# Generated by Django 4.2.17 on 2025-08-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0017_refactor_room_userroom"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="room",
            name="user_one",
        ),
        migrations.RemoveField(
            model_name="room",
            name="user_two",
        ),
    ]
