# Generated by Django 4.2.29 on 2026-04-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0018_alter_room_unique_together_remove_room_user_one_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatModerationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("keep", "Keep"),
                            ("hide", "Hide Message"),
                            ("mute", "Mute User"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("is_automated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="chat_box.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat moderation log",
                "verbose_name_plural": "chat moderation logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["message", "created_at"],
                        name="chat_box_ch_message_5b4754_idx",
                    )
                ],
            },
        ),
    ]
