# Generated by Django 5.2.13 on 2026-05-10 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0019_chatmoderationlog"),
        ("judge", "0241_widen_contest_problem_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmoderationlog",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_moderation_actions",
                to="judge.profile",
            ),
        ),
    ]
