# Generated by Django 5.2.13 on 2026-07-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0020_chatmoderationlog_moderator"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmoderationlog",
            name="mute_duration_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmoderationlog",
            name="mute_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatmoderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("keep", "Keep"),
                    ("hide", "Hide Message"),
                    ("mute", "Mute User"),
                    ("mute_temp", "Temporarily Mute User"),
                    ("mute_perm", "Permanently Mute User"),
                ],
                max_length=20,
            ),
        ),
    ]
