# Generated by Django 5.2.14 on 2026-07-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0021_chat_mute_types"),
        ("judge", "0260_profile_temporary_mute"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[
                            ("like", "👍"),
                            ("love", "❤️"),
                            ("haha", "😆"),
                            ("wow", "😮"),
                            ("sad", "😢"),
                            ("angry", "😠"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chat_box.message",
                        verbose_name="message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="judge.profile",
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "unique_together": {("message", "user")},
            },
        ),
    ]
