# Generated by Django 5.2.13 on 2026-07-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0022_messagereaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagereaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("love", "❤️"),
                    ("haha", "😆"),
                    ("wow", "😮"),
                    ("sad", "😢"),
                    ("angry", "😠"),
                    ("argentina", "🇦🇷"),
                    ("spain", "🇪🇸"),
                    ("goat", "🐐"),
                    ("siuuu", "🐐"),
                ],
                max_length=10,
            ),
        ),
    ]
