# Generated by Django 5.2.13 on 2026-07-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0023_alter_messagereaction_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagereaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("love", "❤️"),
                    ("haha", "😆"),
                    ("wow", "😮"),
                    ("sad", "😢"),
                    ("angry", "😠"),
                ],
                max_length=10,
            ),
        ),
    ]
