# Generated by Django 5.2.13 on 2026-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0024_alter_messagereaction_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmoderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("keep", "Keep"),
                    ("hide", "Hide Message"),
                    ("review", "Needs Review"),
                    ("mute", "Mute User"),
                    ("mute_temp", "Temporarily Mute User"),
                    ("mute_perm", "Permanently Mute User"),
                ],
                max_length=20,
            ),
        ),
    ]
