# Generated by Django 5.2.14 on 2026-08-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0025_alter_chatmoderationlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chat_box.message",
                verbose_name="reply to",
            ),
        ),
    ]
