# Generated by Django 5.2.13 on 2026-09-04 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from ._online_ddl import (
    OnlineMariaDBAddField,
    OnlineMariaDBAddIndex,
    OnlineMariaDBAlterForeignKeyField,
    disable_mariadb_statement_timeout,
    restore_mariadb_statement_timeout,
)


def clear_orphan_message_authors(apps, schema_editor):
    Message = apps.get_model("chat_box", "Message")
    Profile = apps.get_model("judge", "Profile")

    # Do not issue a table-wide UPDATE JOIN here. Production enforces an
    # eight-second statement limit, so scan by primary key and keep every
    # lookup/update bounded to a small batch.
    last_message_id = 0
    while True:
        message_authors = list(
            Message.objects.filter(id__gt=last_message_id)
            .order_by("id")
            .values_list("id", "author_id")[:500]
        )
        if not message_authors:
            break
        last_message_id = message_authors[-1][0]
        author_ids = {
            author_id for _, author_id in message_authors if author_id is not None
        }
        existing_author_ids = set(
            Profile.objects.filter(id__in=author_ids).values_list("id", flat=True)
        )
        orphan_message_ids = [
            message_id
            for message_id, author_id in message_authors
            if author_id is not None and author_id not in existing_author_ids
        ]
        if orphan_message_ids:
            Message.objects.filter(id__in=orphan_message_ids).update(author_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0026_message_reply_to"),
        ("judge", "0271_aiusagelog"),
    ]

    operations = [
        migrations.RunPython(
            disable_mariadb_statement_timeout,
            reverse_code=restore_mariadb_statement_timeout,
        ),
        migrations.CreateModel(
            name="RoomBan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="revoked at"
                    ),
                ),
            ],
            options={
                "verbose_name": "room ban",
                "verbose_name_plural": "room bans",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RoomInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nonce",
                    models.CharField(max_length=64, verbose_name="invitation nonce"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "rotated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="rotated at"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="revoked at"
                    ),
                ),
            ],
            options={
                "verbose_name": "room invitation",
                "verbose_name_plural": "room invitations",
            },
        ),
        migrations.CreateModel(
            name="RoomModerationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Room created"),
                            ("join", "User joined"),
                            ("leave", "User left"),
                            ("add", "User added"),
                            ("remove", "User removed"),
                            ("ban", "User banned"),
                            ("unban", "User unbanned"),
                            ("promote", "User promoted"),
                            ("demote", "User demoted"),
                            ("rename", "Room renamed"),
                            ("archive", "Room archived"),
                            ("restore", "Room restored"),
                            ("invite_rotate", "Invitation rotated"),
                            ("invite_revoke", "Invitation revoked"),
                            ("mute", "User muted"),
                            ("unmute", "User unmuted"),
                            ("hide_message", "Message hidden"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="action",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "room moderation log",
                "verbose_name_plural": "room moderation logs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RoomMute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(verbose_name="duration in days"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="revoked at"
                    ),
                ),
            ],
            options={
                "verbose_name": "room mute",
                "verbose_name_plural": "room mutes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RoomRedirect",
            fields=[
                (
                    "old_room_id",
                    models.PositiveBigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="old room ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="created at",
                    ),
                ),
                (
                    "canonical_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_redirects",
                        to="chat_box.room",
                        verbose_name="canonical room",
                    ),
                ),
            ],
            options={
                "verbose_name": "room redirect",
                "verbose_name_plural": "room redirects",
            },
        ),
        OnlineMariaDBAddField(
            model_name="message",
            name="event_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="system event data"
            ),
        ),
        OnlineMariaDBAddField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[("user", "User message"), ("system", "System message")],
                default="user",
                max_length=16,
                verbose_name="message kind",
            ),
        ),
        OnlineMariaDBAddField(
            model_name="message",
            name="system_event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("join", "User joined"),
                    ("leave", "User left"),
                    ("rename", "Room renamed"),
                ],
                max_length=16,
                null=True,
                verbose_name="system event",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="archive_reason",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="archive reason"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="archived at"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_chat_rooms",
                to="judge.profile",
                verbose_name="archived by",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="channel_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organization", "Organization"),
                    ("custom", "Custom"),
                    ("lobby", "Lobby"),
                ],
                db_index=True,
                max_length=16,
                null=True,
                verbose_name="channel kind",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created at"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="direct_user_high",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_rooms_as_high_user",
                to="judge.profile",
                verbose_name="second direct-message user",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="direct_user_low",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_rooms_as_low_user",
                to="judge.profile",
                verbose_name="first direct-message user",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="last activity at"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="room name"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="organization",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_room",
                to="judge.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="organization_id_snapshot",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="original organization ID",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="organization_name_snapshot",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="original organization name"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct message"),
                    ("group", "Group"),
                    ("channel", "Channel"),
                ],
                db_index=True,
                default="direct",
                max_length=16,
                verbose_name="room type",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="singleton_key",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="singleton key",
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="activated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="activated at"
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="deactivated at"
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="hidden at"),
        ),
        migrations.AddField(
            model_name="userroom",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="room is hidden"
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="joined_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="joined at"
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="last_read_message_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="last read message ID"
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="manual_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=16,
                null=True,
                verbose_name="manual room role",
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                ],
                db_index=True,
                default="member",
                max_length=16,
                null=True,
                verbose_name="effective room role",
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("left", "Left"),
                    ("removed", "Removed"),
                    ("ineligible", "Ineligible"),
                ],
                db_index=True,
                default="active",
                max_length=16,
                verbose_name="membership state",
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="synced_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                ],
                max_length=16,
                null=True,
                verbose_name="synchronized room role",
            ),
        ),
        OnlineMariaDBAlterForeignKeyField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="judge.profile",
                verbose_name="user",
            ),
        ),
        migrations.RunPython(
            restore_mariadb_statement_timeout,
            reverse_code=disable_mariadb_statement_timeout,
        ),
        migrations.RunPython(
            clear_orphan_message_authors,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            disable_mariadb_statement_timeout,
            reverse_code=restore_mariadb_statement_timeout,
        ),
        OnlineMariaDBAlterForeignKeyField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="judge.profile",
                verbose_name="user",
            ),
        ),
        OnlineMariaDBAddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "kind", "hidden", "-id"],
                name="chat_box_me_room_id_beada8_idx",
            ),
        ),
        OnlineMariaDBAddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "author", "time"], name="chat_box_me_room_id_7ff2b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroom",
            index=models.Index(
                fields=["user", "state", "is_hidden", "room"],
                name="chat_box_us_user_id_777255_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userroom",
            index=models.Index(
                fields=["room", "state", "role", "user"],
                name="chat_box_us_room_id_d15599_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("direct_user_low", "direct_user_high"),
                name="chat_unique_direct_user_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("direct_user_low__isnull", True),
                    ("direct_user_high__isnull", True),
                    ("direct_user_low__lte", models.F("direct_user_high")),
                    _connector="OR",
                ),
                name="chat_direct_pair_canonical_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("channel_kind__isnull", True), ("room_type", "direct")),
                    models.Q(("channel_kind__isnull", True), ("room_type", "group")),
                    models.Q(("channel_kind__isnull", False), ("room_type", "channel")),
                    _connector="OR",
                ),
                name="chat_valid_room_type_kind",
            ),
        ),
        migrations.AddField(
            model_name="roomban",
            name="banned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_bans_created",
                to="judge.profile",
                verbose_name="banned by",
            ),
        ),
        migrations.AddField(
            model_name="roomban",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_bans_revoked",
                to="judge.profile",
                verbose_name="revoked by",
            ),
        ),
        migrations.AddField(
            model_name="roomban",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_bans",
                to="chat_box.room",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="roomban",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_bans_received",
                to="judge.profile",
                verbose_name="target user",
            ),
        ),
        migrations.AddField(
            model_name="roominvitation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_room_invitations",
                to="judge.profile",
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="roominvitation",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation",
                to="chat_box.room",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="roommoderationlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_moderation_actions",
                to="judge.profile",
                verbose_name="actor",
            ),
        ),
        migrations.AddField(
            model_name="roommoderationlog",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_moderation_logs",
                to="chat_box.message",
                verbose_name="message",
            ),
        ),
        migrations.AddField(
            model_name="roommoderationlog",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_logs",
                to="chat_box.room",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="roommoderationlog",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_moderation_actions_received",
                to="judge.profile",
                verbose_name="target user",
            ),
        ),
        migrations.AddField(
            model_name="roommute",
            name="muted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_mutes_created",
                to="judge.profile",
                verbose_name="muted by",
            ),
        ),
        migrations.AddField(
            model_name="roommute",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_mutes_revoked",
                to="judge.profile",
                verbose_name="revoked by",
            ),
        ),
        migrations.AddField(
            model_name="roommute",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_mutes",
                to="chat_box.room",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="roommute",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_mutes_received",
                to="judge.profile",
                verbose_name="target user",
            ),
        ),
        migrations.AddIndex(
            model_name="roomban",
            index=models.Index(
                fields=["room", "target", "revoked_at"],
                name="chat_box_ro_room_id_b33589_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roommoderationlog",
            index=models.Index(
                fields=["room", "action", "-created_at"],
                name="chat_box_ro_room_id_e7cb57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roommoderationlog",
            index=models.Index(
                fields=["actor", "action", "-created_at"],
                name="chat_box_ro_actor_i_85a1a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roommute",
            index=models.Index(
                fields=["room", "target", "revoked_at", "expires_at"],
                name="chat_box_ro_room_id_e50bad_idx",
            ),
        ),
        migrations.RunPython(
            restore_mariadb_statement_timeout,
            reverse_code=disable_mariadb_statement_timeout,
        ),
    ]
