# Generated by Django 5.2.13 on 2026-09-06 23:52

import chat_box.models
import django.db.models.deletion
from django.db import migrations, models

from ._online_ddl import (
    OnlineMariaDBAlterForeignKeyField,
    disable_mariadb_statement_timeout,
    restore_mariadb_statement_timeout,
)


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0028_backfill_generalized_rooms"),
        ("judge", "0272_add_room_membership_notification_category"),
    ]

    operations = [
        migrations.RunPython(
            disable_mariadb_statement_timeout,
            reverse_code=restore_mariadb_statement_timeout,
        ),
        migrations.AlterUniqueTogether(
            name="userroom",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="room",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=chat_box.models.room_avatar_path,
                verbose_name="room avatar",
            ),
        ),
        migrations.AddField(
            model_name="userroom",
            name="site_admin_joined",
            field=models.BooleanField(
                default=False, verbose_name="joined through site administration"
            ),
        ),
        OnlineMariaDBAlterForeignKeyField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat_box.room",
                verbose_name="room",
            ),
        ),
        migrations.AlterField(
            model_name="roommoderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Room created"),
                    ("join", "User joined"),
                    ("leave", "User left"),
                    ("add", "User added"),
                    ("remove", "User removed"),
                    ("ban", "User banned"),
                    ("unban", "User unbanned"),
                    ("promote", "User promoted"),
                    ("demote", "User demoted"),
                    ("rename", "Room renamed"),
                    ("archive", "Room archived"),
                    ("restore", "Room restored"),
                    ("invite_rotate", "Invitation rotated"),
                    ("invite_revoke", "Invitation revoked"),
                    ("mute", "User muted"),
                    ("unmute", "User unmuted"),
                    ("hide_message", "Message hidden"),
                    ("avatar_change", "Room avatar changed"),
                ],
                db_index=True,
                max_length=24,
                verbose_name="action",
            ),
        ),
        migrations.AlterField(
            model_name="userroom",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chat_box.room",
                verbose_name="room",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_type", "channel_kind"],
                name="chat_box_ro_room_ty_829049_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["archived_at", "last_activity_at"],
                name="chat_box_ro_archive_3c435e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["organization_id_snapshot"],
                name="chat_box_ro_organiz_10a280_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roomban",
            index=models.Index(
                fields=["room", "revoked_at", "-created_at"],
                name="chat_box_ro_room_id_9d13ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roommoderationlog",
            index=models.Index(
                fields=["room", "-created_at"], name="chat_box_ro_room_id_70dc41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roommute",
            index=models.Index(
                fields=["room", "revoked_at", "expires_at"],
                name="chat_box_ro_room_id_ea4f63_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("name__isnull", True), ("room_type", "direct")),
                    models.Q(
                        ("name__isnull", False),
                        ("room_type", "group"),
                        models.Q(("name", ""), _negated=True),
                    ),
                    models.Q(
                        ("name__isnull", False),
                        ("room_type", "channel"),
                        models.Q(("name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="chat_valid_room_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("avatar__isnull", True),
                    ("avatar", ""),
                    ("room_type", "group"),
                    models.Q(
                        ("channel_kind__in", ("organization", "custom")),
                        ("room_type", "channel"),
                    ),
                    _connector="OR",
                ),
                name="chat_valid_room_avatar",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("channel_kind", "lobby"), ("singleton_key", "lobby")),
                    models.Q(
                        models.Q(("channel_kind", "lobby"), _negated=True),
                        ("singleton_key__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chat_valid_lobby_singleton",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("channel_kind", "organization"),
                        ("organization__isnull", False),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("channel_kind", "organization"),
                        ("organization__isnull", True),
                        ("organization_id_snapshot__isnull", False),
                    ),
                    models.Q(
                        models.Q(("channel_kind", "organization"), _negated=True),
                        ("organization__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chat_valid_room_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("direct_user_high__isnull", False),
                        ("direct_user_low__isnull", False),
                        ("room_type", "direct"),
                    ),
                    models.Q(("archived_at__isnull", False), ("room_type", "direct")),
                    models.Q(
                        models.Q(("room_type", "direct"), _negated=True),
                        ("direct_user_low__isnull", True),
                        ("direct_user_high__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chat_valid_direct_participants",
            ),
        ),
        migrations.AddConstraint(
            model_name="userroom",
            constraint=models.UniqueConstraint(
                fields=("user", "room"), name="chat_unique_user_room_membership"
            ),
        ),
        migrations.RunPython(
            restore_mariadb_statement_timeout,
            reverse_code=disable_mariadb_statement_timeout,
        ),
    ]
