# Generated by Django 5.2.13 on 2026-09-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_box", "0029_finalize_generalized_rooms"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="room",
            name="chat_box_ro_organiz_10a280_idx",
        ),
    ]
