[program:celery]
command=<path to virtualenv>/bin/celery -A dmoj_celery worker --concurrency=4
directory=<path to online-judge>
user=<user>
stdout_logfile=/tmp/celery.stdout.log
stderr_logfile=/tmp/celery.stderr.log
