[program:site]
command=<path to virtualenv>/bin/uwsgi --ini <path to uwsgi.ini>
directory=<path to online-judge>
stopsignal=QUIT
user=<user>
stdout_logfile=/tmp/site.stdout.log
stderr_logfile=/tmp/site.stderr.log
