[program:wsevent]
command=/usr/bin/node <path to online-judge>/websocket/daemon.js
environment=NODE_PATH="<path to online-judge>/node_modules"
user=<user>
stdout_logfile=/tmp/wsevent.stdout.log
stderr_logfile=/tmp/wsevent.stderr.log
